// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0


#ifndef NAT64_USER_LOG_H
#define NAT64_USER_LOG_H

#include "nat64_log_common.h"
#include <bpf/libbpf.h>

#define NAT64_LOG_SOURCE_KERNEL	0
#define NAT64_LOG_SOURCE_USER	1

#define NAT64_LOG_ADD_STR(KEY, VALUE) KEY, NAT64_LOG_TYPE_STR, VALUE
#define NAT64_LOG_ADD_INT(KEY, VALUE) KEY, NAT64_LOG_TYPE_INT, VALUE
#define NAT64_LOG_ADD_UINT(KEY, VALUE) KEY, NAT64_LOG_TYPE_UINT, VALUE
#define NAT64_LOG_ADD_IPV4(KEY, VALUE) KEY, NAT64_LOG_TYPE_IPV4, VALUE
#define NAT64_LOG_ADD_IPV6(KEY, VALUE) KEY, NAT64_LOG_TYPE_IPV6, VALUE


#define NAT64_LOG_VALUE(VALUE) NAT64_LOG_ADD_INT("value", VALUE)
#define NAT64_LOG_IPV4(VALUE) NAT64_LOG_ADD_IPV4("ipv4", VALUE)
#define NAT64_LOG_IPV6(VALUE) NAT64_LOG_ADD_IPV6("ipv6", VALUE)
#define NAT64_LOG_SRC_IPV4(VALUE) NAT64_LOG_ADD_IPV4("src_ipv4", VALUE)
#define NAT64_LOG_DST_IPV4(VALUE) NAT64_LOG_ADD_IPV4("dst_ipv4", VALUE)
#define NAT64_LOG_SRC_IPV6(VALUE) NAT64_LOG_ADD_IPV6("src_ipv6", VALUE)
#define NAT64_LOG_DST_IPV6(VALUE) NAT64_LOG_ADD_IPV6("dst_ipv6", VALUE)
#define NAT64_LOG_L4_PROTOCOL(VALUE) NAT64_LOG_ADD_UINT("l4_protocol", VALUE)
#define NAT64_LOG_IP_VERSION(VALUE) NAT64_LOG_ADD_UINT("ip_version", VALUE)

#define NAT64_LOG_PORT(VALUE) NAT64_LOG_ADD_UINT("port", VALUE)
#define NAT64_LOG_MIN_PORT(VALUE) NAT64_LOG_ADD_UINT("min_port", VALUE)
#define NAT64_LOG_MAX_PORT(VALUE) NAT64_LOG_ADD_UINT("max_port", VALUE)
#define NAT64_LOG_L4_PROTO_PORT(VALUE) NAT64_LOG_ADD_UINT("l4_proto_port", VALUE)
#define NAT64_LOG_L4_PROTO_SRC_PORT(VALUE) NAT64_LOG_ADD_UINT("l4_proto_src_port", VALUE)
#define NAT64_LOG_L4_PROTO_DST_PORT(VALUE) NAT64_LOG_ADD_UINT("l4_proto_dst_port", VALUE)
#define NAT64_LOG_ICMP_TYPE(VALUE) NAT64_LOG_ADD_UINT("icmp_type", VALUE)
#define NAT64_LOG_ICMPV6_TYPE(VALUE) NAT64_LOG_ADD_UINT("icmpv6_type", VALUE)
#define NAT64_LOG_ICMP_IDENTIFIER(VALUE) NAT64_LOG_ADD_UINT("icmp_identifier", VALUE)
#define NAT64_LOG_ICMPV6_IDENTIFIER(VALUE) NAT64_LOG_ADD_UINT("icmpv6_identifier", VALUE)

#define NAT64_LOG_IFACE_INDEX(VALUE) NAT64_LOG_ADD_UINT("iface_index", VALUE)
#define NAT64_LOG_MAP_NAME(VALUE) NAT64_LOG_ADD_STR("map_name", VALUE)

#define NAT64_LOG_ERRNONUM(VALUE) NAT64_LOG_ADD_INT("errno", VALUE)
#define NAT64_LOG_ERRSTR(VALUE) NAT64_LOG_ADD_STR("errstr", VALUE)
#define NAT64_LOG_ERRNO(VALUE) NAT64_LOG_ERRNONUM(VALUE), NAT64_LOG_ERRSTR((strerror(VALUE)))

#define NAT64_LOG_OPT_STR(VALUE) NAT64_LOG_ADD_STR("opt_str", VALUE)


void nat64_macro_log(unsigned int level, unsigned int log_source,
			 const char *message, ...);

#define NAT64_USER_LOG(LEVEL, LOG_SOURCE, MSG, ...) nat64_macro_log(NAT64_LOG_LEVEL_##LEVEL, LOG_SOURCE, MSG, ##__VA_ARGS__, NULL)

#define NAT64_KERN_RINGBUFFER_LOG(LEVEL, MSG, ...) NAT64_USER_LOG(LEVEL, NAT64_LOG_SOURCE_KERNEL, MSG, ##__VA_ARGS__)

#define NAT64_LOG_ERROR(MSG, ...)	NAT64_USER_LOG(ERROR, NAT64_LOG_SOURCE_USER, MSG, ##__VA_ARGS__)
#define NAT64_LOG_WARNING(MSG, ...)	NAT64_USER_LOG(WARNING, NAT64_LOG_SOURCE_USER, MSG, ##__VA_ARGS__)
#define NAT64_LOG_INFO(MSG, ...)	NAT64_USER_LOG(INFO, NAT64_LOG_SOURCE_USER, MSG, ##__VA_ARGS__)
#define NAT64_LOG_DEBUG(MSG, ...)	NAT64_USER_LOG(DEBUG, NAT64_LOG_SOURCE_USER, MSG, ##__VA_ARGS__)


void nat64_kernel_log_printer_loop_exit(void);
void *nat64_thread_process_kernel_log_event(void *arg);
void nat64_set_log_level(uint16_t log_level);
int nat64_libbpf_print_fn(enum libbpf_print_level level, const char *format, va_list args);

#endif
